
spring:
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:30025}
  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_SERVERS:localhost:29092}
      group-id: notification
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true

