apiVersion: v1
kind: Service
metadata:
  name: notification-svc
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  namespace: contract-app
  labels:
    app: notification
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: notification
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: contract-app
  labels:
    app: notification
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: mnikolopoulou/notification:6a074cb58076adfd132dc111767382ada159fc1d
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: MAIL_HOST
              value: "smtp.default.svc.cluster.local"
            - name: MAIL_PORT
              value: "1025"
            - name: KAFKA_SERVERS
              value: "http://kafka-svc.default.svc.cluster.local:9092"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 10
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            failureThreshold: 2
            timeoutSeconds: 10
            successThreshold: 1
          resources:
            limits:
              cpu: 400m
              memory: 300Mi
            requests:
              cpu: 300m
              memory: 200Mi
      terminationGracePeriodSeconds: 60
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: notification-hpa
  namespace: contract-app
  labels:
    app: notification
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notification
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
#    - type: Resource
#      resource:
#        name: memory
#        target:
#          type: Utilization
#          averageUtilization: 100


