apiVersion: apps/v1
kind: Deployment
metadata:
  name: smtp
spec:
  selector:
    matchLabels:
      app: smtp
  template:
    metadata:
      labels:
        app: smtp
    spec:
      containers:
        - name: smtp
          image: dockage/mailcatcher:0.8.2
          ports:
            - name: server
              containerPort: 1025
            - name: client
              containerPort: 1080
---
apiVersion: v1
kind: Service
metadata:
  name: smtp
  labels:
    app: smtp
spec:
  type: NodePort
  selector:
    app: smtp
  ports:
    - port: 1025
      targetPort: 1025
      nodePort: 30025
      name: server
    - port: 1080
      targetPort: 1080
      nodePort: 30080
      name: client
