name: ci-application

on:
  push:
    branches:
      - 'arm64'
    paths:
      - 'application/**'
#      - '.github/workflows/**'

jobs:
  build:
    name: Docker build & push
    runs-on: ubuntu-latest
    steps:
      # Git code checkout
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: arm64

      # Docker Login to Docker registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Docker build & docker push to docker registry
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./application
          platforms: linux/arm64/v8
          file: application/Dockerfile
          push: true
          tags: mnikolopoulou/application:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      CI_COMMIT_MESSAGE: Update image tag
      CI_COMMIT_AUTHOR: GitHub Actions
      CI_COMMIT_EMAIL: ci@github.com
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: arm64
      - run: |
          git config --global user.email "${{ env.CI_COMMIT_EMAIL }}" && git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          echo "updating image tag in application.yaml file"
          sed -i "s,image:.*,image: mnikolopoulou/application:${{ github.sha }}," k8s/app/application.yaml
          git add . && git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
