name: ci-application

on:
  push:
    branches:
      - 'master'
    paths:
      - 'application/**'
      - '.github/workflows/**'

jobs:
  build:
    name: Docker build & push
    runs-on: ubuntu-latest
    steps:
      # Git code checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Docker Login to Docker registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Docker build & docker push to docker registry
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./application
          file: application/Dockerfile
          push: true
          tags: mnikolopoulou/application:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      CI_COMMIT_MESSAGE: Update image tag
      CI_COMMIT_AUTHOR: GitHub Actions
      CI_COMMIT_EMAIL: ci@github.com
    steps:
      - run: |
          git config --global user.email "${{ env.CI_COMMIT_EMAIL }}" && git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          echo "updating image tag in application.yaml file"
          sed -i 's,mnikolopoulou/application,mnikolopoulou/application:${{ github.sha }},' k8s/app/application.yaml
          git add . && git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
