name: ci-gateway

on:
  push:
    branches:
      - 'arm64'
    paths:
      - 'gateway/**'

jobs:
  # Build Stage
  build:
    name: Docker build & push
    runs-on: ubuntu-latest
    steps:
      # Git code checkout
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: arm64

      # Docker Login to Docker registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Docker build & docker push to docker registry
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./gateway
          file: Dockerfile
          push: true
          tags: mnikolopoulou/gateway:${{ github.sha }}
  # Deploy Stage
  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      CI_COMMIT_MESSAGE: Update image tag
      CI_COMMIT_AUTHOR: GitHub Actions
      CI_COMMIT_EMAIL: ci@github.com
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: arm64
      - run: |
          git config --global user.email "${{ env.CI_COMMIT_EMAIL }}" && git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          echo "updating image tag in gateway.yaml file"
          sed -i "s,image:.*,image: mnikolopoulou/gateway:${{ github.sha }}," k8s/app/gateway.yaml
          git add . && git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
