name: ci-gateway

on:
  push:
    branches:
      - 'master'
    paths:
      - 'gateway/**'

jobs:
  build:
    name: Docker build & push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./gateway
          file: Dockerfile
          push: true
          tags: mnikolopoulou/gateway:${{ github.sha }}



